features:
  user_num:
    - "Age"
  user_cat: 
    - "Gender"
    - "Occupation"
    - "Zip-code"
  item_cat: ["Genres"]
  target_col: "target"
  positive_threshold: 3
  train_ratio: 0.8

catboost:
  iterations: 5000
  learning_rate: 0.1
  depth: 6
  loss_function: "YetiRank" # "YetiRank:max_pairs=100"
  task_type: "GPU"
  verbose: 100
  
paths:
  train_data: "data/train.parquet"
  test_data: "data/test.parquet"
  model_output: "models/ranker.cbm"
  embeddings_output: "embeddings"